### ISSUE TITLE
File not found error

### ISSUE THREAD

**Issue by dayal007** [my5G/my5G-non3GPP-access#11]
Hi,

Based on the wiki, https://github.com/my5G/my5G-non3GPP-access/wiki/Setting-up-environment:

The following command fails because that file "/upfcfg.sample1.yaml" doesn't exists.

# New configuration for upf
cp src/upf/config/upfcfg.sample1.yaml src/upf/build/config/upfcfg.yaml

Thanks,
Udhay

**Comment by mariotlemes** [comment]
Hello,

The file for UPF configuration:

(upfcfg.sample1.zip](https://github.com/my5G/my5G-non3GPP-access/files/6451367/upfcfg.sample1.zip)

Regards,
Mario

**Comment by dayal007** [comment]
> Hello,
> 
> The file for UPF configuration:
> 
> (upfcfg.sample1.zip](https://github.com/my5G/my5G-non3GPP-access/files/6451367/upfcfg.sample1.zip)
> 
> Regards,
> Mario

Hello,

Yes. But the issue was created for documentation. The location or instruction was not specified in the wiki and the documentation need to be fixed.

Thanks,
Udhay
