### ISSUE TITLE
Testing UE-IoT-non3GPP with free5gC

### ISSUE THREAD

**Issue by raoufkh** [my5G/my5G-non3GPP-access#2]
Hello!

I would want to know if there is anyone who has tested this project with the free5gC? If yes it has worked fine?

We're working on the deployment of free5gC on top of Kubernetes. Furthermore, we've deployed the [UERANSIM](https://github.com/aligungr/UERANSIM) and all works fine when enabling the ULCL feature and when not. I'd like to add the UE-IoT-non3GPP simulator to my project so anyone has already tested it?

Thank you in advance!

**Comment by mariotlemes** [comment]
@raoufkh,

Firstly, i'm sorry for the late reply. 

I didn't tested [non3GPP-access](https://github.com/my5G/my5G-non3GPP-access) with free5GC, directly. However, non3GPP-access is built over [my5G-core](https://github.com/my5G/my5G-core) that is currently a fork of the free5GC project, with some extensions to facilitate the deployment.

We recently added a [use case](https://github.com/my5G/my5G-non3GPP-access/wiki) using an wifi connection as a non-trusted access network and works successful with my5G-core and non3GPP-access. Maybe it might be interesting for you.

**Comment by mariotlemes** [comment]
> Hello!
> 
> I would want to know if there is anyone who has tested this project with the free5gC? If yes it has worked fine?
> 
> We're working on the deployment of free5gC on top of Kubernetes. Furthermore, we've deployed the [UERANSIM](https://github.com/aligungr/UERANSIM) and all works fine when enabling the ULCL feature and when not. I'd like to add the UE-IoT-non3GPP simulator to my project so anyone has already tested it?
> 
> Thank you in advance!

@raoufkh,

Firstly, i'm sorry for the late reply. 

I didn't tested [non3GPP-access](https://github.com/my5G/my5G-non3GPP-access) with free5GC, directly. However, non3GPP-access is built over [my5G-core](https://github.com/my5G/my5G-core) that is currently a fork of the free5GC project, with some extensions to facilitate the deployment.

We recently added a [use case](https://github.com/my5G/my5G-non3GPP-access/wiki) using an wifi connection as a non-trusted access network and works successful with my5G-core and non3GPP-access. Maybe it might be interesting for you.

**Comment by raoufkh** [comment]
Hello!

First of all, thank you for response! 

If I understand correctly, the use of an AP is an extra usecase? If this is the case, we'll try first to establish the simpler one from the [Usage](https://github.com/my5G/my5G-non3GPP-access/wiki/Usage) section in the WIKI in order to simulate a non3gpp access. For that, can you provide more information on the parameters to pass to the script, please?
 - What do `ue_addr` and `ue_port` refer to?
 - Is `n3iwf_address` the IP address used by the **N3IWF** for the IKE daemon?
 - Is `ike_bind_addr` the IP address which should be used by the **my5G-non3GPP-access**? If true I guess that it must be in the same network as the one used by the **N3IWF" for the same purpose.

Best regards,
Raouf

**Comment by mariotlemes** [comment]
Hello!

> If I understand correctly, the use of an AP is an extra usecase? Yes! The non-3GPP-acess wifi use-case uses an wifi connection instead of virtual ethernet (veth) between UE (User Equipment) and N3IWF, directly. The simpler use of non3GPP-access uses a veth (generic conection) to connect UE and N3IWF. Note that i refer UE instead of non3GPP-access because non-3GPP-access uses an UE NAS signalling.

> * What do `ue_addr` and `ue_port` refer to? This parameters indicates the ipv4 address of UE (User Equipment) and the port  which the UE is listening to trigger procedures. This [material](https://github.com/LABORA-INF-UFG/SBrT2020-Minicurso1/blob/master/docs/5gs-procedures/initial-registration-procedure.md) can be usefull for more informations.

> * Is `n3iwf_address` the IP address used by the **N3IWF** for the IKE daemon? Yes, the n3iwf_address is the IPv4 address used  by N3IWF to communicate directly with UE. In the material that I mentioned in above question, the ip address of N3IWF for IKE daemon is 192.168.127.1/24.

> * Is `ike_bind_addr` the IP address which should be used by the **my5G-non3GPP-access** for the IKE daemon? If true I guess that it must be in the same network as the one used by the **N3IWF** for the same purpose. Yes, ike_bind_address is the ipv4 address of UE to communicate directly with N3IWF component. As in previous answer, the ip address of UE for IKE daemon is 192.168.127.2/24. Therefore, UE and N3IWF are in the same subnet (192.168.127.0/24).

> For our deployment of the Free5gc, the N3IWF has 3 interfaces (the first with AMF, the second with UPF and the third for connection with UPF), exactly as mentioned [here](https://github.com/free5gc/free5gc/wiki/Run#b-run-the-n3iwf-individually). Is the same configuration. N3IWF has 3 interfaces: the first connects to the AMF, the second connects to the UPF, and the third is for IKE daemon (connect with UE).

Best regards,
Mario

**Comment by raoufkh** [comment]
Hello Mario

Thank you very much for this clear explanation! 

Regards,
Raouf
