### ISSUE TITLE
UE Build Not Working

### ISSUE THREAD

**Issue by dayal007** [my5G/my5G-non3GPP-access#5]
non 3gpp code is not working. getting and error while building ue

$ go build -o bin/ue -x src/ue/src/ue/ue.go
WORK=/tmp/go-build757043628
src/ue/src/ue/ue.go:7:2: package free5gc/src/ue/logger is not in GOROOT (/usr/local/go/src/free5gc/src/ue/logger)
src/ue/src/ue/ue.go:8:2: package free5gc/src/ue/service is not in GOROOT (/usr/local/go/src/free5gc/src/ue/service)
src/ue/src/ue/ue.go:9:2: package free5gc/src/ue/version is not in GOROOT (/usr/local/go/src/free5gc/src/ue/version)

**Comment by mariotlemes** [comment]
Hello @dayal007!

Can you check the building process again? There was really a problem with the code of non-3GPP access, but we've already solved it.

Make yourself comfortable to contact if you still have problems.

Thank you for interest in non3GPP-access project.

Best regards,
Mario

**Comment by dayal007** [comment]
> Hello @dayal007!
> 
> Can you check the building process again? There was really a problem with the code of non-3GPP access, but we've already solved it.
> 
> Make yourself comfortable to contact if you still have problems.
> 
> Thank you for interest in non3GPP-access project.
> 
> Best regards,
> Mario

**Comment by dayal007** [comment]
Hello @mariotlemes 

Thanks a lot. The build issue is fixed but I am still not able to connect the ue to the my5gcore. There are several issues with the documentation and help.

If this project really need to be successful and useful to others, then the documentation need to be clear.

Is this a love project or just under maintenance only?

Thanks,
Udhay

**Comment by mariotlemes** [comment]
Hello @dayal007 

> There are several issues with the documentation and help.

Can you list the several issues that you found? This will help the better organization of tutorial information.

> If this project really need to be successful and useful to others, then the documentation need to be clear.

> Is this a love project or just under maintenance only?

non3GPP-access is a part of my5G that is an open-source software initiative focused on making 5G systems modular and easy to deploy and operate. Therefore, you can help with proposal of *pull requests* for improve the documentation. For contribution, please reference to [guidelines](https://github.com/my5G/template/blob/main/CONTRIBUTING.md).

Regards,
Mario

**Comment by dayal007** [comment]
Hello @mariotlemes,

Sure, that's a great idea. I will do it.

I am closing this issue since the build is fixed now.

Thanks,
Udhay
