### ISSUE TITLE
UEns dhclient wlan1 - No IP address assigned

### ISSUE THREAD

**Issue by dayal007** [my5G/my5G-non3GPP-access#6]
Hello,

The following command doesnt return 

 sudo ip netns exec UEns dhclient wlan1

Later when I cancel the command using Ctrl +C:

No IP Address assigned.

# sudo ip netns exec UEns ip addr show wlan1
12: wlan1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 02:00:00:00:01:00 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::ff:fe00:100/64 scope link
       valid_lft forever preferred_lft forever

Thanks,
Udhay

**Comment by mariotlemes** [comment]
Hello, 

I can not reproduce your issue. To help, this picture shows the tutorial commands performed in sequence. As can be seen, in checking terminal, the wlan1 obtains the IP 192.168.1.1/24 after the dhclient command (see the last command in first terminal).

![Captura de Tela 2021-05-02 às 10 11 38](https://user-images.githubusercontent.com/11560302/116814652-610db400-ab30-11eb-92d8-446cb245604d.png)

I suggest that you see the [general information](https://github.com/my5G/my5G-non3GPP-access/wiki/General-information) to verify the environment that non-3GPP-access wifi use-case has been tested.
 
Regards,
Mario

**Comment by dayal007** [comment]
Hello @mariotlemes,

Thanks a lot again. I understood the mistake I did. I executed both the "echo $BASHPID" command in the second terminal. Once I execute the second "echo $BASHPID" in the third terminal, it worked fine.

Thanks,
Udhay
