### ISSUE TITLE
Error when executing fix_core.sh

### ISSUE THREAD

**Issue by dayal007** [my5G/my5G-non3GPP-access#8]
Hi,

There is a bug in the fix_core.sh shell script and it fails here:

# compiling gtp5g module
cd ~/gtp5g
sudo make && sudo make install

Full error:

sudo ./sample/my5g_wifi_config/utils/fix_core.sh
net.ipv4.ip_forward = 1
Stopping ufw (via systemctl): ufw.service.
./sample/my5g_wifi_config/utils/fix_core.sh: line 10: cd: /root/gtp5g: No such file or directory
make: *** No targets specified and no makefile found.  Stop.

**Comment by dayal007** [comment]
I am trying to avoid creating multiple issues, here is one more:

cp src/upf/config/upfcfg.sample1.yaml src/upf/build/config/upfcfg.yaml
cp: cannot stat 'src/upf/config/upfcfg.sample1.yaml': No such file or directory

**Comment by dayal007** [comment]
Ok I think, I found the issue.

When I use the instructions from https://github.com/my5G/my5G-non3GPP-access/wiki/Install-from-source, then I get the errors. But when I install my5g-core from the link https://github.com/my5G/my5G-core/wiki and then just follow https://github.com/my5G/my5G-non3GPP-access/wiki/Install-from-source , everything went fine.

**Comment by mariotlemes** [comment]
Hello @dayal007,

> Hi,
> 
> There is a bug in the fix_core.sh shell script and it fails here:
> 
> # compiling gtp5g module
> cd ~/gtp5g
> sudo make && sudo make install
> 
> Full error:
> 
> sudo ./sample/my5g_wifi_config/utils/fix_core.sh
> net.ipv4.ip_forward = 1
> Stopping ufw (via systemctl): ufw.service.
> ./sample/my5g_wifi_config/utils/fix_core.sh: line 10: cd: /root/gtp5g: No such file or directory
> make: *** No targets specified and no makefile found. Stop.

Probably you are trying to execute the command in a directory that not contains the gtp5g module. I suspect that the module gpt5g should be installed in your home user (~/gtp5g) and not inside the root dir (root/gtp5g).

> I am trying to avoid creating multiple issues, here is one more:
> 
> cp src/upf/config/upfcfg.sample1.yaml src/upf/build/config/upfcfg.yaml
> cp: cannot stat 'src/upf/config/upfcfg.sample1.yaml': No such file or directory

For some reason the file *src/upf/config/upfcfg.sample1.yaml* is not in directory. If you execute the tutorial and doest not performed the step for [cleanning the environment](https://github.com/my5G/my5G-non3GPP-access/wiki/Cleanning-up-environment), this error may occur. Therefore, always clean the environment before run the tutorial for a second time.

> Ok I think, I found the issue.
> 
> When I use the instructions from https://github.com/my5G/my5G-non3GPP-access/wiki/Install-from-source, then I get the errors. But when I install my5g-core from the link https://github.com/my5G/my5G-core/wiki and then just follow https://github.com/my5G/my5G-non3GPP-access/wiki/Install-from-source , everything went fine.

Exactly. As can be seen in [general information](https://github.com/my5G/my5G-non3GPP-access/wiki/General-information), this guide assumes that you will run all 5GC elements on a single machine and that my5G-core and UE are already installed in ~/my5G-core and ~/my5G-core/src/ue, respectivaly. 

Regards,
Mario
